name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install dependences
        run: npm install esm

      - name: Deploy 🚀
        uses: actions/setup-node@v1
      - run: npm run deploy ${{ steps.extract_branch.outputs.branch }} ${{ secrets.GITHUB_TOKEN }}
